version: '2'
services:
  web:
    build: .
    image: nodejs
    container_name: api-nodejs
    command: npm start
    ports:
      - "7000:7000"
    links:
      - mongo
    environment:
      DATABASE_URL: mongodb://127.0.0.1/userManager
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
